#!/usr/bin/env python3
"""
Security Report Generator
Runs all scanners and generates a comprehensive security report
"""

import sys
import os
import requests
from datetime import datetime
from urllib.parse import urlparse

# Add parent directory to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from scanners import recon, header_check, dir_enum, sqli_check
from rich.console import Console

console = Console()


def banner():
    """Display report generator banner"""
    console.print("\n[bold cyan]📊 Security Report Generator[/bold cyan]")
    console.print("[dim]Running comprehensive security assessment...[/dim]\n")


def run_recon_scan(url):
    """Run reconnaissance scan"""
    console.print("[yellow]⏳ Running reconnaissance scan...[/yellow]")
    try:
        response = requests.get(url, timeout=10)
        headers = dict(response.headers)
        
        # Get page title
        from bs4 import BeautifulSoup
        soup = BeautifulSoup(response.text, 'html.parser')
        title = soup.find('title')
        title_text = title.string if title else "No title"
        
        return {
            'status': 'success',
            'status_code': response.status_code,
            'headers': headers,
            'title': title_text,
            'response_time': response.elapsed.total_seconds()
        }
    except Exception as e:
        return {'status': 'error', 'message': str(e)}


def run_header_scan(url):
    """Run security header scan"""
    console.print("[yellow]⏳ Running security header scan...[/yellow]")
    try:
        response = requests.get(url, timeout=10)
        headers = dict(response.headers)
        
        analysis = header_check.analyze_headers(headers)
        insecure = header_check.check_insecure_headers(headers)
        
        return {
            'status': 'success',
            'analysis': analysis,
            'insecure_headers': insecure
        }
    except Exception as e:
        return {'status': 'error', 'message': str(e)}


def run_directory_scan(url):
    """Run directory enumeration"""
    console.print("[yellow]⏳ Running directory enumeration...[/yellow]")
    try:
        if not url.endswith('/'):
            url += '/'
        
        found = dir_enum.scan_directories(url)
        
        return {
            'status': 'success',
            'found': found,
            'total_checked': len(dir_enum.WORDLIST)
        }
    except Exception as e:
        return {'status': 'error', 'message': str(e)}


def run_sqli_scan(url):
    """Run SQL injection scan"""
    console.print("[yellow]⏳ Running SQL injection scan...[/yellow]")
    
    # Try common login endpoints
    login_paths = ['/login', '/auth', '/signin']
    
    for path in login_paths:
        test_url = url.rstrip('/') + path
        try:
            response = requests.get(test_url, timeout=5)
            if response.status_code == 200:
                console.print(f"[dim]Testing endpoint: {test_url}[/dim]")
                vulnerabilities = sqli_check.test_sqli(test_url)
                return {
                    'status': 'success',
                    'endpoint': test_url,
                    'vulnerabilities': vulnerabilities
                }
        except:
            continue
    
    return {'status': 'skipped', 'message': 'No login endpoint found'}


def generate_markdown_report(url, results, output_file='security_report.md'):
    """Generate Markdown report"""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    report = f"""# Security Assessment Report

**Target:** {url}  
**Date:** {timestamp}  
**Generated by:** Security Testing Lab

---

## Executive Summary

This report contains the results of an automated security assessment performed on the target application.

"""
    
    # Calculate overall risk
    critical_issues = 0
    high_issues = 0
    medium_issues = 0
    low_issues = 0
    
    # Reconnaissance
    report += "## 1. Reconnaissance\n\n"
    if results['recon']['status'] == 'success':
        report += f"- **Status Code:** {results['recon']['status_code']}\n"
        report += f"- **Page Title:** {results['recon']['title']}\n"
        report += f"- **Response Time:** {results['recon']['response_time']:.2f}s\n"
        report += f"- **Total Headers:** {len(results['recon']['headers'])}\n\n"
    else:
        report += f"⚠️ Error: {results['recon'].get('message', 'Unknown error')}\n\n"
    
    # Security Headers
    report += "## 2. Security Headers Analysis\n\n"
    if results['headers']['status'] == 'success':
        analysis = results['headers']['analysis']
        score = analysis['score']
        max_score = analysis['max_score']
        percentage = (score / max_score) * 100
        
        report += f"**Security Score:** {score}/{max_score} ({percentage:.1f}%)\n\n"
        
        if analysis['present']:
            report += "### ✅ Headers Present\n\n"
            for item in analysis['present']:
                report += f"- **{item['header']}:** `{item['value'][:60]}`\n"
            report += "\n"
        
        if analysis['missing']:
            report += "### ❌ Headers Missing\n\n"
            for item in analysis['missing']:
                severity = item['info']['severity']
                if severity == 'HIGH':
                    high_issues += 1
                elif severity == 'MEDIUM':
                    medium_issues += 1
                else:
                    low_issues += 1
                
                report += f"- **{item['header']}** [{severity}]\n"
                report += f"  - {item['info']['description']}\n"
                report += f"  - Recommendation: `{item['info']['recommendation']}`\n\n"
        
        # Information disclosure
        if results['headers']['insecure_headers']:
            report += "### ⚠️ Information Disclosure\n\n"
            for item in results['headers']['insecure_headers']:
                medium_issues += 1
                report += f"- **{item['header']}:** `{item['value']}`\n"
                report += f"  - Issue: {item['issue']}\n\n"
    else:
        report += f"⚠️ Error: {results['headers'].get('message', 'Unknown error')}\n\n"
    
    # Directory Enumeration
    report += "## 3. Directory Enumeration\n\n"
    if results['directory']['status'] == 'success':
        found = results['directory']['found']
        total = results['directory']['total_checked']
        
        report += f"**Paths Checked:** {total}  \n"
        report += f"**Paths Found:** {len(found)}\n\n"
        
        if found:
            report += "### Discovered Paths\n\n"
            report += "| Path | Status | Size | Notes |\n"
            report += "|------|--------|------|-------|\n"
            
            for item in found[:20]:  # Limit to first 20
                size = item['size']
                size_str = f"{size / 1024:.1f} KB" if size > 1024 else f"{size} B"
                notes = ""
                if item['redirect']:
                    notes = f"Redirects to {item['redirect'][:30]}"
                elif item['status'] == 403:
                    notes = "Access denied"
                    low_issues += 1
                
                report += f"| `{item['path']}` | {item['status']} | {size_str} | {notes} |\n"
            
            report += "\n"
            
            # Check for sensitive paths
            sensitive = [p for p in found if any(
                keyword in p['path'].lower()
                for keyword in ['admin', 'config', 'backup', '.git', '.env', 'api']
            )]
            
            if sensitive:
                report += "### 🔴 Sensitive Paths Detected\n\n"
                for path in sensitive:
                    medium_issues += 1
                    report += f"- `{path['path']}` [{path['status']}]\n"
                report += "\n"
    else:
        report += f"⚠️ Error: {results['directory'].get('message', 'Unknown error')}\n\n"
    
    # SQL Injection
    report += "## 4. SQL Injection Testing\n\n"
    if results['sqli']['status'] == 'success':
        vulns = results['sqli']['vulnerabilities']
        endpoint = results['sqli']['endpoint']
        
        report += f"**Tested Endpoint:** {endpoint}\n\n"
        
        if vulns:
            critical_issues += len(vulns)
            report += f"### 🚨 CRITICAL: SQL Injection Vulnerabilities Detected\n\n"
            report += f"**{len(vulns)} vulnerability(ies) found**\n\n"
            
            report += "| Payload | Type | Detection Reason |\n"
            report += "|---------|------|------------------|\n"
            
            for vuln in vulns:
                report += f"| `{vuln['payload']}` | {vuln['description']} | {vuln['reason']} |\n"
            
            report += "\n"
            report += "**Impact:**\n"
            report += "- Authentication bypass\n"
            report += "- Unauthorized data access\n"
            report += "- Data manipulation/deletion\n"
            report += "- Potential system compromise\n\n"
            
            report += "**Remediation:**\n"
            report += "1. Use parameterized queries (prepared statements)\n"
            report += "2. Implement input validation and sanitization\n"
            report += "3. Use ORM frameworks\n"
            report += "4. Apply principle of least privilege for database accounts\n\n"
        else:
            report += "✅ No SQL injection vulnerabilities detected\n\n"
    elif results['sqli']['status'] == 'skipped':
        report += f"⚠️ {results['sqli'].get('message', 'Scan skipped')}\n\n"
    else:
        report += f"⚠️ Error: {results['sqli'].get('message', 'Unknown error')}\n\n"
    
    # Summary
    report += "## 5. Risk Summary\n\n"
    report += f"- **Critical Issues:** {critical_issues}\n"
    report += f"- **High Issues:** {high_issues}\n"
    report += f"- **Medium Issues:** {medium_issues}\n"
    report += f"- **Low Issues:** {low_issues}\n\n"
    
    total_issues = critical_issues + high_issues + medium_issues + low_issues
    
    if critical_issues > 0:
        risk_level = "CRITICAL"
        risk_color = "🔴"
    elif high_issues > 0:
        risk_level = "HIGH"
        risk_color = "🟠"
    elif medium_issues > 0:
        risk_level = "MEDIUM"
        risk_color = "🟡"
    elif low_issues > 0:
        risk_level = "LOW"
        risk_color = "🟢"
    else:
        risk_level = "MINIMAL"
        risk_color = "✅"
    
    report += f"**Overall Risk Level:** {risk_color} {risk_level}\n\n"
    
    # Recommendations
    report += "## 6. Recommendations\n\n"
    
    if critical_issues > 0:
        report += "### Immediate Action Required\n\n"
        report += "1. **Fix SQL injection vulnerabilities immediately**\n"
        report += "   - This is a critical security flaw that can lead to complete system compromise\n"
        report += "   - Implement parameterized queries\n\n"
    
    if high_issues > 0:
        report += "### High Priority\n\n"
        report += "1. **Implement missing security headers**\n"
        report += "   - Add Content-Security-Policy\n"
        report += "   - Add Strict-Transport-Security\n\n"
    
    if medium_issues > 0:
        report += "### Medium Priority\n\n"
        report += "1. **Address information disclosure**\n"
        report += "   - Remove server version headers\n"
        report += "   - Restrict access to sensitive paths\n\n"
    
    report += "### General Recommendations\n\n"
    report += "1. Implement a Web Application Firewall (WAF)\n"
    report += "2. Regular security testing and code reviews\n"
    report += "3. Keep all software and dependencies updated\n"
    report += "4. Implement proper logging and monitoring\n"
    report += "5. Follow OWASP Top 10 guidelines\n\n"
    
    # Footer
    report += "---\n\n"
    report += "*This report was generated by the security testing lab. "
    report += "Manual verification and additional testing is recommended.*\n"
    
    # Write report
    with open(output_file, 'w') as f:
        f.write(report)
    
    return output_file


def main():
    """Main entry point"""
    if len(sys.argv) < 2:
        console.print("[red]Usage: python generate_report.py <target_url>[/red]")
        console.print("[dim]Example: python generate_report.py http://localhost:5000[/dim]")
        sys.exit(1)
    
    target = sys.argv[1]
    
    # Validate URL
    parsed = urlparse(target)
    if not parsed.scheme:
        target = f"http://{target}"
    
    banner()
    console.print(f"[bold]Target:[/bold] {target}\n")
    
    # Run all scans
    results = {
        'recon': run_recon_scan(target),
        'headers': run_header_scan(target),
        'directory': run_directory_scan(target),
        'sqli': run_sqli_scan(target)
    }
    
    # Generate report
    console.print("\n[yellow]⏳ Generating report...[/yellow]")
    output_file = generate_markdown_report(target, results)
    
    console.print(f"\n[green]✓ Report generated:[/green] {output_file}")
    console.print(f"[dim]View with: cat {output_file}[/dim]\n")


if __name__ == '__main__':
    main()
